/** Fonte única de texto do /admin, irmã de content-plataforma.ts. */
export const admin = {
  nome: "Administração",
  shell: {
    metricas: "Métricas",
    alunos: "Alunos",
    conteudo: "Conteúdo",
    configuracoes: "Configurações",
    verComoAluno: "Ver como aluno",
  },
  alunos: {
    titulo: "Alunos",
    buscarPlaceholder: "Buscar por nome ou e-mail",
    buscarBotao: "Buscar",
    vazio: "Nenhum aluno encontrado.",
    colunas: {
      nome: "Nome",
      email: "E-mail",
      status: "Status",
      ultimoAcesso: "Último acesso",
      criadoEm: "Criado em",
    },
    seloAdmin: "Admin",
    seloDesativada: "Desativada",
    nuncaAcessou: "—",
    paginacao: {
      anterior: "Anterior",
      proxima: "Próxima",
    },
    detalhe: {
      voltar: "Voltar para Alunos",
      dadosConta: "Dados da conta",
      assinatura: "Assinatura",
      progresso: "Progresso nos cursos",
      semProgresso: "Ainda não começou nenhum curso.",
      semHistorico: "Nenhuma alteração de assinatura ainda.",
      acoes: "Ações",
    },
    acoes: {
      liberarAcesso: "Liberar acesso",
      revogarAcesso: "Revogar acesso",
      tornarAdmin: "Tornar admin",
      tornarAluno: "Tornar aluno",
      desativarConta: "Desativar conta",
      reativarConta: "Reativar conta",
      excluirConta: "Excluir conta",
      confirmarExclusaoTexto: "Isso apaga a conta, o progresso e o histórico de assinatura. Não pode ser desfeito.",
      campoEmailConfirmacao: "Digite o e-mail do aluno para confirmar",
      botaoConfirmarExclusao: "Excluir definitivamente",
      emailNaoConfere: "O e-mail digitado não confere.",
    },
    mensagens: {
      acessoLiberado: "Acesso liberado.",
      acessoRevogado: "Acesso revogado.",
      salvo: "Salvo.",
      contaDesativada: "Conta desativada.",
      contaReativada: "Conta reativada.",
      contaExcluida: "Conta excluída.",
      erroAuto: "Você não pode fazer isso com a própria conta.",
      erroGenerico: "Não foi possível concluir a ação.",
      jaTemAcesso: "Este aluno já tem acesso liberado.",
      jaSemAcesso: "Este aluno já não tem acesso.",
    },
  },
} as const;
