/** Fonte única de texto do /admin, irmã de content-plataforma.ts. */
export const admin = {
  nome: "Administração",
  shell: {
    metricas: "Métricas",
    alunos: "Alunos",
    conteudo: "Conteúdo",
    configuracoes: "Configurações",
    verComoAluno: "Ver como aluno",
  },
  alunos: {
    titulo: "Alunos",
    buscarPlaceholder: "Buscar por nome ou e-mail",
    buscarBotao: "Buscar",
    vazio: "Nenhum aluno encontrado.",
    colunas: {
      nome: "Nome",
      email: "E-mail",
      status: "Status",
      ultimoAcesso: "Último acesso",
      criadoEm: "Criado em",
    },
    seloAdmin: "Admin",
    seloDesativada: "Desativada",
    nuncaAcessou: "—",
    paginacao: {
      anterior: "Anterior",
      proxima: "Próxima",
    },
    detalhe: {
      voltar: "Voltar para Alunos",
      dadosConta: "Dados da conta",
      assinatura: "Assinatura",
      progresso: "Progresso nos cursos",
      semProgresso: "Ainda não começou nenhum curso.",
      semHistorico: "Nenhuma alteração de assinatura ainda.",
      acoes: "Ações",
    },
    acoes: {
      liberarAcesso: "Liberar acesso",
      revogarAcesso: "Revogar acesso",
      tornarAdmin: "Tornar admin",
      tornarAluno: "Tornar aluno",
      desativarConta: "Desativar conta",
      reativarConta: "Reativar conta",
      excluirConta: "Excluir conta",
      confirmarExclusaoTexto: "Isso apaga a conta, o progresso e o histórico de assinatura. Não pode ser desfeito.",
      campoEmailConfirmacao: "Digite o e-mail do aluno para confirmar",
      botaoConfirmarExclusao: "Excluir definitivamente",
      emailNaoConfere: "O e-mail digitado não confere.",
    },
    mensagens: {
      acessoLiberado: "Acesso liberado.",
      acessoRevogado: "Acesso revogado.",
      salvo: "Salvo.",
      contaDesativada: "Conta desativada.",
      contaReativada: "Conta reativada.",
      contaExcluida: "Conta excluída.",
      erroAuto: "Você não pode fazer isso com a própria conta.",
      erroGenerico: "Não foi possível concluir a ação.",
      jaTemAcesso: "Este aluno já tem acesso liberado.",
      jaSemAcesso: "Este aluno já não tem acesso.",
    },
  },
  conteudo: {
    titulo: "Conteúdo",
    vazio: "Nenhum curso cadastrado ainda.",
    colunas: {
      titulo: "Título",
      status: "Status",
      aulas: "Aulas",
    },
    seloPublicado: "Publicado",
    seloOculto: "Oculto",
    seloSemVideo: (n: number) => `${n} sem vídeo`,
    seloAulaSemVideo: "sem vídeo",
    novoCurso: {
      botao: "Novo curso",
      campoTitulo: "Título do curso",
    },
    campos: {
      titulo: "Título",
      slug: "Endereço (slug)",
      descricao: "Descrição",
      capaUrl: "URL da capa",
      nivel: "Nível",
      cargaHoras: "Carga horária (h)",
      ordem: "Ordem",
    },
    niveis: ["Iniciante", "Intermediário", "Avançado"],
    botaoSalvar: "Salvar",
    botaoPublicar: "Publicar",
    botaoOcultar: "Ocultar",
    modulos: {
      titulo: "Módulos",
      vazio: "Nenhum módulo ainda.",
      botaoNovoModulo: "Novo módulo",
      campoTitulo: "Título do módulo",
      campoRenomear: "Renomear módulo",
      subir: "Subir",
      descer: "Descer",
      botaoSalvarTitulo: "Salvar título",
    },
    aulas: {
      vazio: "Nenhuma aula neste módulo ainda.",
      botaoNovaAula: "Nova aula",
      campoTitulo: "Título da aula",
      campos: {
        titulo: "Título",
        slug: "Endereço (slug)",
        descricao: "Descrição",
        duracaoSeg: "Duração (segundos)",
        gratuita: "Gratuita (não exige assinatura)",
      },
      midia: {
        titulo: "Vídeo",
        provider: "Provedor",
        videoId: "ID do vídeo",
        vazio: "Sem vídeo cadastrado — o aluno verá \"em produção\".",
        botaoSalvar: "Salvar vídeo",
        botaoRemover: "Remover vídeo",
      },
    },
    avisos: {
      aulasSemVideo: (n: number) =>
        `Publicado. Atenção: ${n} aulas ainda sem vídeo — o aluno verá "em produção".`,
      alunosAtivos: "Ocultado. Atenção: há alunos com progresso registrado neste curso.",
    },
    confirmarExclusao: {
      texto: (n: number, m: number) => `Isto apaga ${n} aulas e o progresso de ${m} alunos. Digite EXCLUIR para confirmar.`,
      campoLabel: "Digite EXCLUIR para confirmar",
      palavra: "EXCLUIR",
      naoConfere: "Digite EXCLUIR (em maiúsculas) para confirmar.",
      excluirCurso: "Excluir curso",
      excluirModulo: "Excluir módulo",
      excluirAula: "Excluir aula",
    },
    erros: {
      slugExiste: "Já existe conteúdo com esse endereço (slug).",
      generico: "Não foi possível concluir a ação.",
      cursoPublicado: "Este curso está publicado — oculte antes de excluir.",
    },
    mensagens: {
      salvo: "Salvo.",
      cursoCriado: "Curso criado.",
      moduloCriado: "Módulo criado.",
      aulaCriada: "Aula criada.",
      excluido: "Excluído.",
      midiaSalva: "Vídeo salvo.",
      midiaRemovida: "Vídeo removido.",
      publicado: "Publicado.",
      ocultado: "Ocultado.",
    },
  },
  metricas: {
    titulo: "Métricas",
    periodo: {
      rotulo: "Período",
      "7": "7 dias",
      "30": "30 dias",
      "90": "90 dias",
      tudo: "Tudo",
    },
    cartoes: {
      alunosTotais: "Alunos totais",
      novos: "Novos alunos",
      assinaturasAtivas: "Assinaturas ativas",
      alunosAtivos: "Alunos ativos",
      aulasConcluidas: "Aulas concluídas",
    },
    graficos: {
      cadastros: "Cadastros por semana",
      atividade: "Atividade por semana",
      colunaSemana: "Semana",
      colunaValor: "Valor",
    },
    semDados: "Sem dados para este período.",
    conclusao: {
      titulo: "Conclusão por curso",
      curso: "Curso",
      comecaram: "Começaram",
      concluiram: "Concluíram",
      percentual: "%",
      vazio: "Nenhum curso publicado ainda.",
    },
    funil: {
      titulo: "Funil de conclusão",
      vazio: "Este curso ainda não tem aulas.",
      semCurso: "Nenhum curso publicado ainda.",
    },
    exportarCsv: "Exportar CSV",
  },
  configuracoes: {
    titulo: "Configurações",
    campos: {
      ctaDestino: "Destino do botão de venda (URL)",
      avisoTopo: "Aviso no topo da área do aluno (vazio = sem aviso)",
      emailContato: "E-mail de contato",
    },
    salvar: "Salvar",
    salvo: "Salvo.",
    erros: {
      urlInvalida: "Informe uma URL válida (comece com / ou https://)",
    },
  },
} as const;
