/**
 * Fonte única de texto da plataforma (/app), irmã de lib/content.ts.
 * Mesma regra do site: nenhuma string visível mora em componente.
 */
export const plataforma = {
  nome: "IAgentics Academy",
  shell: {
    meusCursos: "Meus cursos",
    conta: "Conta",
    /* Só aparece para admin, conferido no banco (nunca no JWT). */
    administracao: "Administração",
    sair: "Sair",
  },
  entrar: {
    titulo: "Entrar na plataforma",
    email: "E-mail",
    senha: "Senha",
    botao: "Entrar",
    semConta: "Ainda não tem conta?",
    criarConta: "Criar conta",
    erroCredenciais: "E-mail ou senha incorretos",
    sessaoExpirada: "Sua sessão expirou. Entre de novo para continuar.",
    naoConfirmado: "Confirme seu e-mail antes de entrar. Não recebeu o link?",
    esqueciSenha: "Esqueci minha senha",
  },
  criarConta: {
    titulo: "Criar conta",
    nome: "Nome",
    email: "E-mail",
    senha: "Senha",
    botao: "Criar conta",
    jaTem: "Já tem conta?",
    entrar: "Entrar",
    emailExiste: "Este e-mail já tem conta. Entre com sua senha ou peça um link de acesso.",
    nomeCurto: "Informe seu nome completo.",
    senhaCurta: "A senha precisa de pelo menos 8 caracteres.",
  },
  confirmacao: {
    titulo: "Confirme seu e-mail",
    enviamos: (email: string) => `Enviamos um link de confirmação para ${email}. Abra o e-mail e clique no link para entrar.`,
    reenviar: "Reenviar link",
    reenviado: "Se existir uma conta com este e-mail, enviamos um novo link.",
    linkInvalidoTitulo: "Link inválido ou vencido",
    linkInvalidoTexto: "Peça um novo link de confirmação informando seu e-mail.",
    jaConfirmado: "Se você já confirmou, é só entrar com sua senha.",
    irParaLogin: "Ir para o login",
    confirmadoAviso: "E-mail confirmado — entre com sua senha.",
  },
  painel: {
    continuar: "Continue de onde parou",
    catalogo: "Cursos",
    seloAssine: "Assine para acessar",
    seloConcluida: "Concluída",
    ctaAssinar: "Assinar agora",
    /* Redesign editorial: trilhos por estado do aluno + hero. */
    emAndamento: "Em andamento",
    formacoes: "Formações",
    concluidos: "Concluídos",
    emGravacao: "Em gravação",
    continuarAula: (titulo: string) => `Continuar: ${titulo}`,
    boasVindas: "Bem-vindo à Academy",
    bannerTitulo: "Todo o acervo, no seu ritmo.",
    boasVindasTexto:
      "Formações completas, aulas novas toda semana e progresso salvo — escolha por onde começar nos trilhos abaixo.",
    cursoConcluido: "Curso concluído",
    horas: "h",
  },
  curso: {
    continuar: "Continuar",
    comecar: "Começar o curso",
    gratis: "Grátis",
    aulas: "aulas",
    concluidaDe: (feitas: number, total: number) => `${feitas} de ${total} aulas concluídas`,
    /* Curso publicado antes das aulas existirem (catálogo espelha o site). */
    emProducao: "As aulas deste curso estão em gravação e chegam em breve.",
  },
  aula: {
    marcarConcluida: "Marcar como concluída",
    proximaAula: "Próxima aula",
    concluida: "Aula concluída",
    bloqueadaTitulo: "Esta aula faz parte da assinatura",
    bloqueadaTexto: "Assine o acervo da Academy para assistir esta e todas as outras aulas.",
    bloqueadaCta: "Assinar agora",
    semVideo: "Esta aula está em produção. O vídeo chega em breve.",
    videoFalhou: "O vídeo não carregou.",
    videoIndisponivel: "Este vídeo está indisponível — privado ou sem permissão de reprodução fora do YouTube.",
    recarregar: "Recarregar",
    aulasDoCurso: "Aulas do curso",
    aulaDe: (x: number, y: number) => `Aula ${x} de ${y}`,
    /* Controles do player próprio (moldura sobre o embed do YouTube). */
    player: {
      reproduzir: "Reproduzir",
      pausar: "Pausar",
      progresso: "Progresso do vídeo",
      velocidade: "Velocidade de reprodução",
      semSom: "Desativar som",
      comSom: "Ativar som",
      telaCheia: "Tela cheia",
      sairTelaCheia: "Sair da tela cheia",
    },
  },
  conta: {
    titulo: "Sua conta",
    nome: "Nome",
    email: "E-mail",
    salvar: "Salvar",
    salvo: "Salvo.",
    trocarSenha: "Trocar senha",
    novaSenha: "Nova senha",
    senhaAtual: "Senha atual",
    senhaAtualErrada: "Senha atual incorreta.",
    senhaTrocada: "Senha atualizada.",
    senhaTrocaFalhou: "Não foi possível trocar a senha. Recarregue a página e tente de novo.",
    assinatura: "Assinatura",
    statusAtiva: (ate: string) => `Ativa até ${ate}`,
    statusManual: "Liberada manualmente",
    statusInadimplente: "Pagamento pendente",
    statusPendente: "Aguardando confirmação do pagamento",
    statusCancelada: "Cancelada",
    statusNenhuma: "Sem assinatura",
    certificados: "Certificados",
    semCertificados: "Nenhum certificado ainda — conclua uma formação.",
  },
  planos: {
    eyebrow: "Assinatura",
    titulo: "Todo o acervo da Academy. Um plano só.",
    preco: "R$ 39,90",
    porMes: "/mês",
    beneficios: [
      "Acesso total a todas as formações do catálogo — e às que chegarem",
      "Aulas novas conforme saem da gravação",
      "Assista no seu ritmo, de qualquer dispositivo",
      "Cancele quando quiser, sem multa",
    ],
    cta: "Assinar agora",
    jaAssinante: "Você já é assinante.",
    irParaPlataforma: "Ir para a plataforma",
    cursosTitulo: "O que está dentro",
    descricaoMeta: "Assinatura do acervo IAgentics Academy: todas as formações por R$ 39,90 por mês.",
  },
  certificado: {
    titulo: "Certificado de conclusão",
    emissor: "IAgentics Academy",
    concluiuA: "concluiu a formação",
    seloValido: "✓ Certificado válido",
    autenticidade: "Emitido por IAgentics Academy. Este endereço confirma a autenticidade do certificado.",
    cargaHoraria: "Carga horária",
    emitidoEm: "Emitido em",
    codigo: "Código de validação",
    adicionarLinkedin: "Adicionar ao LinkedIn",
    compartilharLinkedin: "Compartilhar no LinkedIn",
    imprimir: "Imprimir / salvar PDF",
    verCertificado: "Ver certificado",
    // Valor que aparece como organização emissora no formulário do LinkedIn.
    organizacaoLinkedin: "IAgentics",
    metaTitulo: (formacao: string) => `Certificado — ${formacao} · IAgentics Academy`,
    metaDescricao: (aluno: string, formacao: string) => `${aluno} concluiu a formação ${formacao} na IAgentics Academy.`,
  },
  recuperarSenha: {
    titulo: "Esqueci minha senha",
    texto: "Informe seu e-mail. Se houver uma conta, enviaremos o link de redefinição.",
    botao: "Enviar link",
    enviado: "Se existir uma conta com este e-mail, enviamos o link de redefinição.",
    novaTitulo: "Escolha a nova senha",
    novaTexto: "O link é de uso único. Salve a senha nova para entrar.",
    novaSenha: "Nova senha",
    botaoSalvar: "Salvar nova senha",
    linkInvalidoTitulo: "Link inválido ou vencido",
    linkInvalidoTexto: "Links de redefinição valem por 60 minutos e funcionam uma vez.",
    pedirNovo: "Pedir um novo link",
    redefinidaAviso: "Senha redefinida — entre com a nova senha.",
    senhaCurta: "A senha precisa de pelo menos 8 caracteres.",
  },
  assinar: {
    titulo: "Assinar a Academy",
    resumo:
      "Plano mensal de R$ 39,90 com acesso total ao acervo. O pagamento acontece na página segura do Asaas — Pix, cartão ou boleto.",
    cpf: "CPF",
    cpfAjuda: "Usado só para emitir a cobrança no Asaas. Não fica guardado aqui.",
    botao: "Ir para o pagamento",
    cpfInvalido: "CPF inválido. Confira os números e tente de novo.",
    jaAssinante: "Você já é assinante.",
    erroGenerico: "Não foi possível iniciar o pagamento. Tente novamente em instantes.",
  },
  /* E-mails transacionais (lib/plataforma/email.ts). Texto puro + HTML simples
     da marca; link também em texto puro por entregabilidade. */
  emails: {
    confirmacao: {
      assunto: "Confirme seu e-mail — IAgentics Academy",
      saudacao: (nome: string) => `Olá, ${nome}.`,
      corpo: "Confirme seu e-mail para entrar na IAgentics Academy. O link vale por 7 dias.",
      botao: "Confirmar e-mail",
      ignorar: "Se você não criou esta conta, ignore esta mensagem.",
    },
    reset: {
      assunto: "Redefinir sua senha — IAgentics Academy",
      saudacao: (nome: string) => `Olá, ${nome}.`,
      corpo: "Recebemos um pedido para redefinir sua senha. O link vale por 60 minutos e funciona uma única vez.",
      botao: "Redefinir senha",
      ignorar: "Se você não pediu a redefinição, ignore esta mensagem — sua senha continua a mesma.",
    },
    copie: "Ou copie e cole:",
    rodape: "IAgentics Academy · iagentics.com.br",
  },
} as const;
